name = "SpecAugment"
uuid = "03bfb08c-7145-41e0-9a8a-bfc2110fc62b"
version = "0.1.0"
authors = ["Sole sonosole@163.com>"]


[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Plots", "Test"]
